language: scala
scala:
    - 2.10.6
    - 2.11.8
jdk:
    - oraclejdk7

matrix:
  include:
  - scala: 2.12.0
    jdk: oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION scalastyle coverage test
after_success: sbt coveralls
